Spring:
  datasource:
    #配置数据源类型
    url: jdbc:mysql://localhost:3306/Chicken_sales_platform?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zzn
  #配置redis
  redis:
    host: 192.168.200.131
    port: 6380
    password: zzn199636520
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 192.168.200.131 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: zzn # 用户名
    password: zzn199636520 # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
#  web:
#    resources:
#      static-locations: file:D:\Image\ChickenImage\

#配置mybatis规则
mybatis:
  type-aliases-package: com.zhao.salechicken.pojo
  mapper-locations: classpath:/mapper/*.xml #mybatis的sql映射文件
  configuration: #指定MyBatis全集配置文件中的关键配置项
    map-underscore-to-camel-case: true #开启驼峰映射

#分页插件的配置
pagehelper:
  #配置四項 hprs
  helper-dialect: mysql  #分页助手方言：mysql
  params: count=countSql  #为了支持 startPage(Object params) 方法
  support-methods-arguments: true  #支持通过 Mapper 接口参数来传递分页参数，默认值 false
  reasonable: true #分页合理化参数，默认值为 false,页码不为负，不超总页码

#图片存放路径
salechicken:
  path: D:\Image\ChickenImage\

server:
  port: 9999